# Generated by Django 4.2.20 on 2025-06-13 22:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=50)),
                ('acc_number', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=50, verbose_name='Bank Name')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Payment Category',
                'verbose_name_plural': 'Payment Categories',
            },
        ),
        migrations.CreateModel(
            name='PaymentChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('term', models.CharField(blank=True, choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term'), ('Others', 'Others')], max_length=50)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('desc', models.CharField(blank=True, max_length=150)),
                ('payment_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentcategory')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.session')),
            ],
            options={
                'verbose_name': 'Payment Chart',
                'verbose_name_plural': 'Payment Chart',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid_a', models.DecimalField(decimal_places=2, default=0.0, help_text='First Payment Amount', max_digits=15, null=True, verbose_name='1st Payment')),
                ('payment_date_a', models.DateField(verbose_name='Payment Date')),
                ('remark_a', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('amount_paid_b', models.DecimalField(decimal_places=2, default=0.0, help_text='Second Payment Amount', max_digits=15, null=True, verbose_name='2nd Payment')),
                ('payment_date_b', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('remark_b', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('amount_paid_c', models.DecimalField(decimal_places=2, default=0.0, help_text='Third Payment Amount', max_digits=15, null=True, verbose_name='3rd Payment')),
                ('payment_date_c', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('remark_c', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('discount', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='enter in (%) leave empty if no discoun is given', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='TOTAL DISCOUNT(if any)')),
                ('confirmed_a', models.BooleanField(default=False)),
                ('confirmed_b', models.BooleanField(default=False)),
                ('confirmed_c', models.BooleanField(default=False)),
                ('trans_id', models.CharField(blank=True, max_length=8)),
                ('payment_updated_date', models.DateField(auto_now_add=True)),
                ('bank_name_a', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_a', to='payments.bankdetail', verbose_name='Bank Account')),
                ('bank_name_b', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_b', to='payments.bankdetail', verbose_name='Bank Account')),
                ('bank_name_c', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.bankdetail', verbose_name='Bank Account')),
                ('payee', models.ForeignKey(default=None, help_text='confirm student username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_detail', to=settings.AUTH_USER_MODEL)),
                ('payment_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payment_type', to='payments.paymentchart')),
            ],
            options={
                'verbose_name': 'Payment Detail',
                'verbose_name_plural': 'Payment Detail',
                'ordering': ['-payee'],
                'unique_together': {('payee', 'payment_name')},
            },
        ),
    ]
