# Generated by Django 4.2.20 on 2025-04-18 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=50)),
                ('acc_number', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=50, verbose_name='Bank Name')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Payment Category',
                'verbose_name_plural': 'Payment Categories',
            },
        ),
        migrations.CreateModel(
            name='PaymentChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('term', models.CharField(blank=True, choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term'), ('Others', 'Others')], max_length=50)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('desc', models.CharField(blank=True, max_length=150)),
                ('payment_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentcategory')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.session')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid_a', models.DecimalField(decimal_places=2, default=0.0, help_text='First Payment Amount', max_digits=15, null=True)),
                ('payment_date_a', models.DateField()),
                ('remark_a', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('amount_paid_b', models.DecimalField(decimal_places=2, default=0.0, help_text='Second Payment Amount', max_digits=15, null=True)),
                ('payment_date_b', models.DateField(blank=True, null=True)),
                ('remark_b', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('amount_paid_c', models.DecimalField(decimal_places=2, default=0.0, help_text='Third Payment Amount', max_digits=15, null=True)),
                ('payment_date_c', models.DateField(blank=True, null=True)),
                ('remark_c', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('discount', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='enter in (%) leave empty if no discoun is given', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='TOTAL DISCOUNT(if any)')),
                ('confirmed_a', models.BooleanField(default=False)),
                ('confirmed_b', models.BooleanField(default=False)),
                ('confirmed_c', models.BooleanField(default=False)),
                ('payment_updated_date', models.DateField(auto_now_add=True)),
                ('bank_name_a', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_name_a', to='payments.bankdetail')),
                ('bank_name_b', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_name_b', to='payments.bankdetail')),
                ('bank_name_c', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.bankdetail')),
                ('payment_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payment_name', to='payments.paymentchart')),
                ('student_detail', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-student_detail'],
                'unique_together': {('student_detail', 'payment_name')},
            },
        ),
    ]
