# Generated by Django 4.2.20 on 2025-05-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='receipt_header',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
