# Generated by Django 4.2.20 on 2025-05-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentdetail_receipt_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='receipt_header',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='trans_id',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
