# Generated by Django 4.2.20 on 2025-06-08 08:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_paymentdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='user',
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='amount_paid_a',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='First Payment Amount', max_digits=15, null=True, verbose_name='1st Payment'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='amount_paid_b',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Second Payment Amount', max_digits=15, null=True, verbose_name='2nd Payment'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='amount_paid_c',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Third Payment Amount', max_digits=15, null=True, verbose_name='3rd Payment'),
        ),
        migrations.CreateModel(
            name='PaymentDetail1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid_a', models.DecimalField(decimal_places=2, default=0.0, help_text='First Payment Amount', max_digits=15, null=True)),
                ('payment_date_a', models.DateField()),
                ('remark_a', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('amount_paid_b', models.DecimalField(decimal_places=2, default=0.0, help_text='Second Payment Amount', max_digits=15, null=True)),
                ('payment_date_b', models.DateField(blank=True, null=True)),
                ('remark_b', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('amount_paid_c', models.DecimalField(decimal_places=2, default=0.0, help_text='Third Payment Amount', max_digits=15, null=True)),
                ('payment_date_c', models.DateField(blank=True, null=True)),
                ('remark_c', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('discount', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='enter in (%) leave empty if no discoun is given', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='TOTAL DISCOUNT(if any)')),
                ('confirmed_a', models.BooleanField(default=False)),
                ('confirmed_b', models.BooleanField(default=False)),
                ('confirmed_c', models.BooleanField(default=False)),
                ('trans_id', models.CharField(blank=True, max_length=8)),
                ('payment_updated_date', models.DateField(auto_now_add=True)),
                ('bank_name_a', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_a', to='payments.bankdetail')),
                ('bank_name_b', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_b', to='payments.bankdetail')),
                ('bank_name_c', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.bankdetail')),
                ('payee', models.ForeignKey(default=None, help_text='confirm student username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_detail', to=settings.AUTH_USER_MODEL)),
                ('payment_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payment_type', to='payments.paymentchart')),
            ],
            options={
                'ordering': ['-payee'],
                'unique_together': {('payee', 'payment_name')},
            },
        ),
    ]
