# Generated by Django 4.2.20 on 2025-06-10 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_paymentdetail_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentchart',
            options={'verbose_name': 'Payment Chart', 'verbose_name_plural': 'Payment Chart'},
        ),
        migrations.AlterModelOptions(
            name='paymentdetail1',
            options={'ordering': ['-payee'], 'verbose_name': 'Payment Detail', 'verbose_name_plural': 'Payment Detail'},
        ),
        migrations.AlterField(
            model_name='paymentdetail1',
            name='amount_paid_a',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='First Payment Amount', max_digits=15, null=True, verbose_name='1st Payment'),
        ),
        migrations.AlterField(
            model_name='paymentdetail1',
            name='amount_paid_b',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Second Payment Amount', max_digits=15, null=True, verbose_name='2nd Payment'),
        ),
        migrations.AlterField(
            model_name='paymentdetail1',
            name='amount_paid_c',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Third Payment Amount', max_digits=15, null=True, verbose_name='3rd Payment'),
        ),
        migrations.AlterField(
            model_name='paymentdetail1',
            name='bank_name_a',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_a', to='payments.bankdetail', verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='paymentdetail1',
            name='bank_name_b',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_b', to='payments.bankdetail', verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='paymentdetail1',
            name='bank_name_c',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.bankdetail', verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='paymentdetail1',
            name='payment_date_a',
            field=models.DateField(verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='paymentdetail1',
            name='payment_date_b',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='paymentdetail1',
            name='payment_date_c',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.DeleteModel(
            name='PaymentDetail',
        ),
    ]
