# Generated by Django 4.2.20 on 2025-06-13 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('USN', models.CharField(help_text='Unique Student Number, Must be same as username', max_length=100, primary_key='True', serialize=False)),
                ('full_name', models.CharField(help_text='First_Name, Middle_name, Last_Name', max_length=200)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('select_gender', 'select_gender')], default='select_gender', max_length=20)),
                ('DOB', models.DateField(default='1998-01-01')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'B-'), ('B+', 'B+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('select', 'select')], default='select', max_length=15)),
                ('genotype', models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS'), ('select', 'select')], default='select', max_length=15)),
                ('health_remark', models.CharField(default='enter health detail', max_length=60, null=True)),
                ('student_type', models.CharField(choices=[('day_student', 'day_student'), ('boarder', 'boarder')], default='day_student', max_length=15)),
                ('date_admitted', models.DateField(default='2020-01-01')),
                ('guardian_name', models.CharField(max_length=60)),
                ('guardian_address', models.TextField(blank=True, max_length=120)),
                ('guardian_phone', models.CharField(blank=True, max_length=15)),
                ('guardian_email', models.CharField(blank=True, max_length=30)),
                ('relationship', models.CharField(choices=[('select', 'select'), ('parent', 'parent'), ('father', 'father'), ('mother', 'mother'), ('sister', 'sister'), ('brother', 'brother'), ('aunt', 'aunt'), ('uncle', 'uncle'), ('other', 'other')], default='select', help_text="Guardian's Relationship With Student", max_length=25)),
                ('student_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('graduated', 'graduated'), ('dropped', 'dropped'), ('expelled', 'expelled'), ('suspended', 'suspended')], default='active', max_length=15)),
                ('badge', models.ForeignKey(blank=True, default='not a prefect', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.badge', verbose_name='Prefect Tittle (if is prefect)')),
                ('class_id', models.ForeignKey(default=1, help_text='The Student Current Class', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='curriculum.standard')),
                ('class_on_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_on_admission', to='curriculum.standard', verbose_name='class_on_admission')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='staff.teacher')),
                ('hostel_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_name', to='students.hostel', verbose_name='hostel')),
                ('user', models.OneToOneField(help_text='select user or add a new user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='StudentId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.BooleanField(default=False)),
                ('f_1', models.ImageField(default='school_id_header.jpg', help_text='Do not upload file', upload_to='school_logo')),
                ('f_2', models.ImageField(default='qr_code.jpg', help_text='Do not upload file', upload_to='school_logo')),
                ('f_3', models.ImageField(default='sign.jpg', help_text='Do not upload file', upload_to='school_logo')),
                ('student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idcardimage', to='students.student')),
            ],
            options={
                'verbose_name': 'Confirm to enable student generate ID Card',
            },
        ),
    ]
