# Generated by Django 4.2.20 on 2025-04-18 19:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('USN', models.CharField(help_text='Unique Student Number', max_length=100, primary_key='True', serialize=False)),
                ('full_name', models.CharField(help_text='First_Name, Middle_name, Last_Name', max_length=200)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('select_gender', 'select_gender')], default='select_gender', max_length=20)),
                ('DOB', models.DateField(default='1998-01-01')),
                ('student_type', models.CharField(choices=[('day_student', 'day_student'), ('boarder', 'boarder')], default='day_student', max_length=15)),
                ('date_admitted', models.DateField(default='2020-01-01')),
                ('guardian_name', models.CharField(max_length=60)),
                ('guardian_address', models.TextField(blank=True, max_length=120)),
                ('guardian_phone', models.CharField(blank=True, max_length=15)),
                ('guardian_email', models.CharField(blank=True, max_length=30)),
                ('relationship', models.CharField(choices=[('select', 'select'), ('parent', 'parent'), ('father', 'father'), ('mother', 'mother'), ('sister', 'sister'), ('brother', 'brother'), ('aunt', 'aunt'), ('uncle', 'uncle'), ('other', 'other')], default='select', help_text="Guardian's Relationship With Student", max_length=25)),
                ('student_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('graduated', 'graduated'), ('dropped', 'dropped'), ('expelled', 'expelled'), ('suspended', 'suspended')], default='active', max_length=15)),
                ('badge', models.ForeignKey(blank=True, default='not a prefect', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.badge', verbose_name='Prefect Tittle (if is prefect)')),
                ('class_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.class')),
                ('class_on_admission', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_on_admission', to='curriculum.class', verbose_name='class_on_admission')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
            ],
            options={
                'verbose_name_plural': 'Marks',
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='MarksClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Internal test 1', 'Internal test 1'), ('Internal test 2', 'Internal test 2'), ('Internal test 3', 'Internal test 3'), ('Event 1', 'Event 1'), ('Event 2', 'Event 2'), ('Semester End Exam', 'Semester End Exam')], default='Internal test 1', max_length=50)),
                ('status', models.BooleanField(default='False')),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.assign')),
            ],
            options={
                'unique_together': {('assign', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Internal test 1', 'Internal test 1'), ('Internal test 2', 'Internal test 2'), ('Internal test 3', 'Internal test 3'), ('Event 1', 'Event 1'), ('Event 2', 'Event 2'), ('Semester End Exam', 'Semester End Exam')], default='Internal test 1', max_length=50)),
                ('marks1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('studentcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentsubject')),
            ],
            options={
                'unique_together': {('studentcourse', 'name')},
            },
        ),
    ]
