# Generated by Django 4.2.20 on 2025-05-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_hostel_student_hostel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'B-'), ('B+', 'B+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('select', 'select')], default='select', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='genotype',
            field=models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS'), ('select', 'select')], default='select', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='health_remark',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
