# Generated by Django 4.2.20 on 2025-06-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_phone_home_alter_teacher_phone_home'),
        ('students', '0002_alter_student_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='hostel_master',
            field=models.ForeignKey(help_text='select hostel master', null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.teacher'),
        ),
    ]
