# Generated by Django 4.2.20 on 2025-06-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_blood_group_student_genotype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user']},
        ),
        migrations.AlterField(
            model_name='student',
            name='health_remark',
            field=models.CharField(default='enter health detail', max_length=60, null=True),
        ),
    ]
