# Generated by Django 4.2.20 on 2025-06-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_options_alter_student_health_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.BooleanField(default=False)),
                ('f_1', models.ImageField(default='school_id_header.jpg', help_text='Do not upload file', upload_to='school_logo')),
                ('f_2', models.ImageField(default='qr_code.jpg', help_text='Do not upload file', upload_to='school_logo')),
                ('f_3', models.ImageField(default='sign.jpg', help_text='Do not upload file', upload_to='school_logo')),
                ('student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idcardimage', to='students.student')),
            ],
            options={
                'verbose_name': 'Re-confirm Publish to enable student view result',
            },
        ),
    ]
