# Generated by Django 4.2.20 on 2025-06-02 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentid',
            options={'verbose_name': 'Confirm to enable student generate ID Card'},
        ),
    ]
