# Generated by Django 4.2.20 on 2025-06-05 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_schoolidentity_options_and_more'),
        ('students', '0006_alter_studentid_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='curriculum.class'),
        ),
    ]
