# Generated by Django 4.2.20 on 2025-06-06 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffposition_options_alter_staffposition_slug'),
        ('students', '0007_alter_student_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='staff.teacher'),
        ),
    ]
