# Generated by Django 4.2.20 on 2025-06-06 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_schoolidentity_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0008_student_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='USN',
            field=models.CharField(help_text='Unique Student Number, Must be same as username', max_length=100, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(default=1, help_text='The Student Current Class', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='curriculum.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_on_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_on_admission', to='curriculum.class', verbose_name='class_on_admission'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(help_text='select user or add a new user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
