# Generated by Django 4.2.20 on 2025-06-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffposition',
            options={'verbose_name': 'Staff Position', 'verbose_name_plural': 'Staff Position'},
        ),
        migrations.AlterField(
            model_name='staffposition',
            name='slug',
            field=models.SlugField(blank=True, help_text='Do not enter anything here', null=True),
        ),
    ]
