# Generated by Django 4.2.20 on 2025-06-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone_home',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_home',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
