# Generated by Django 4.2.20 on 2025-06-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_alter_schoolidentity_options'),
        ('staff', '0002_alter_staffposition_options_alter_staffposition_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.class'),
        ),
    ]
