# Generated by Django 4.2.20 on 2025-06-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
