# Generated by Django 4.2.20 on 2025-06-16 18:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'verbose_name_plural': 'Standard Section'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['position'], 'verbose_name': 'E-Learning Lessons', 'verbose_name_plural': 'E-Learning Lessons'},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'verbose_name': 'Standards', 'verbose_name_plural': 'Standards'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'E-Learning Subjects', 'verbose_name_plural': 'E-Learning Subjects'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='Notes',
            field=models.FileField(blank=True, upload_to='https://fadanohell.org.ng/schoollyfiles/', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
