# Generated by Django 4.2.20 on 2025-06-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='teachers_id',
            new_name='teachers',
        ),
    ]
