# Generated by Django 4.2.23 on 2025-06-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolidentity',
            name='logo',
            field=models.ImageField(default='school_logo.jpg', help_text='must not exceed 180px by 180px in size', upload_to='official_pics'),
        ),
    ]
