# Generated by Django 4.2.20 on 2025-06-16 18:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_classgroup_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='Notes',
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher_note',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes',
            field=models.FileField(blank=True, upload_to='save_lesson_files', verbose_name='Notes'),
        ),
    ]
