# Generated by Django 4.2.20 on 2025-06-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_comment_reply_lesson_comment_lesson_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=60)),
                ('phone1', models.CharField(max_length=11)),
                ('phone2', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('logo', models.ImageField(default='default.jpg', help_text='must not exceed 1800 by 180 pixel', upload_to='official_pics')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
