# Generated by Django 4.2.20 on 2025-06-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_remove_lesson_notes_lesson_teacher_note_lesson_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher_note',
        ),
    ]
