# Generated by Django 4.2.20 on 2025-06-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_schoolidentity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolidentity',
            options={'verbose_name_plural': 'School Identity'},
        ),
        migrations.RenameField(
            model_name='schoolidentity',
            old_name='address',
            new_name='address_line_1',
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='phone2',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
