# Generated by Django 4.2.20 on 2025-06-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_schoolidentity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolidentity',
            name='logo',
            field=models.ImageField(default='default.jpg', help_text='must not exceed 180px by 180px in size', upload_to='official_pics'),
        ),
    ]
