# Generated by Django 4.2.20 on 2025-06-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_schoolidentity_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolidentity',
            options={'verbose_name_plural': 'School Identity Settings'},
        ),
    ]
