# Generated by Django 4.2.20 on 2025-06-09 19:00

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_alter_schoolidentity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='comment',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
