# Generated by Django 4.2.20 on 2025-06-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_subject_slug_alter_lesson_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subjects', 'verbose_name_plural': 'Subjects'},
        ),
    ]
