# Generated by Django 4.2.20 on 2025-06-14 11:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('route_id', models.CharField(blank=True, max_length=8, null=True)),
                ('direction', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('driver', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_driver', to='staff.staff')),
                ('staff_in_charge', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_staff', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='BusFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, help_text='Bus Fare', max_digits=15, null=True, verbose_name='Bus Fare')),
                ('route', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='route_name', to='transport.route')),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='academic_session', to='curriculum.session')),
                ('term', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='term_name', to='curriculum.session')),
            ],
            options={
                'ordering': ['-amount_due'],
            },
        ),
        migrations.CreateModel(
            name='StudentBusPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid_a', models.DecimalField(decimal_places=2, default=0.0, help_text='First Payment Amount', max_digits=15, null=True)),
                ('payment_date_a', models.DateField()),
                ('remark_a', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('amount_paid_b', models.DecimalField(decimal_places=2, default=0.0, help_text='Second Payment Amount', max_digits=15, null=True)),
                ('payment_date_b', models.DateField(blank=True, null=True)),
                ('remark_b', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('amount_paid_c', models.DecimalField(decimal_places=2, default=0.0, help_text='Third Payment Amount', max_digits=15, null=True)),
                ('payment_date_c', models.DateField(blank=True, null=True)),
                ('remark_c', models.CharField(blank=True, max_length=200, verbose_name='description(if any)')),
                ('discount', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='enter in (%) leave empty if no discoun is given', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='TOTAL DISCOUNT(if any)')),
                ('confirmed_a', models.BooleanField(default=False)),
                ('confirmed_b', models.BooleanField(default=False)),
                ('confirmed_c', models.BooleanField(default=False)),
                ('payment_updated_date', models.DateField(auto_now_add=True)),
                ('bank_name_a', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_name_a', to='payments.bankdetail')),
                ('bank_name_b', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_name_b', to='payments.bankdetail')),
                ('bank_name_c', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.bankdetail')),
                ('payee_id', models.ForeignKey(default=None, help_text='confirmusername', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transport.busfee')),
                ('route', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.route')),
            ],
            options={
                'ordering': ['-payee_id'],
                'unique_together': {('payee_id', 'route')},
            },
        ),
    ]
